import { 
  Flame, 
  Keyboard, 
  Moon, 
  PenTool, 
  Wand2, 
  UploadCloud, 
  Theater, 
  Layers, 
  CheckCircle2, 
  Users, 
  MessageSquare, 
  CornerDownRight, 
  BookOpen, 
  Library, 
  Clock, 
  Star, 
  MessageCircle, 
  Heart, 
  UserPlus, 
  Calendar,
  Award
} from 'lucide-react';

export type BadgeTier = 'bronze' | 'silver' | 'gold' | 'diamond' | 'special';
export type BadgeCategory = 'writer_production' | 'writer_publishing' | 'reader_consumption' | 'reader_interaction';

export interface BadgeConfig {
  id: string;
  title: string;
  description: string;
  icon: any; // Lucide icon component
  tier: BadgeTier;
  category: BadgeCategory;
  conditionDescription: string;
}

export const BADGES: Record<string, BadgeConfig> = {
  // --- 1. Üretim ve İstikrar (Yazarlar İçin) ---
  first_spark: {
    id: 'first_spark',
    title: 'İlk Kıvılcım',
    description: 'Yazarlık serüvenindeki ilk adımı attın.',
    icon: Flame,
    tier: 'special',
    category: 'writer_production',
    conditionDescription: 'Editörde ilk 500 kelimeyi yazma.',
  },
  keyboard_breaker_bronze: {
    id: 'keyboard_breaker_bronze',
    title: 'Klavye Aşındıran (Bronz)',
    description: 'Kelimeler parmaklarından dökülüyor.',
    icon: Keyboard,
    tier: 'bronze',
    category: 'writer_production',
    conditionDescription: 'Editörde toplam 10.000 kelimeye ulaşma.',
  },
  keyboard_breaker_silver: {
    id: 'keyboard_breaker_silver',
    title: 'Klavye Aşındıran (Gümüş)',
    description: 'Artık klavyen senin bir parçan oldu.',
    icon: Keyboard,
    tier: 'silver',
    category: 'writer_production',
    conditionDescription: 'Editörde toplam 50.000 kelimeye ulaşma.',
  },
  keyboard_breaker_gold: {
    id: 'keyboard_breaker_gold',
    title: 'Klavye Aşındıran (Altın)',
    description: 'Roman ustası kıvamına geldin.',
    icon: Keyboard,
    tier: 'gold',
    category: 'writer_production',
    conditionDescription: 'Editörde toplam 100.000 kelimeye ulaşma.',
  },
  night_shift_writer: {
    id: 'night_shift_writer',
    title: 'Gece Mesaisi',
    description: 'Gece herkes uyurken sen dünyalar yaratıyorsun.',
    icon: Moon,
    tier: 'silver',
    category: 'writer_production',
    conditionDescription: 'Gece 00:00 ile 04:00 saatleri arasında kesintisiz en az 1 saat editörde aktif olma.',
  },
  steady_pen_3: {
    id: 'steady_pen_3',
    title: 'İstikrarlı Kalem (3 Gün)',
    description: 'Alışkanlıklar 3 günde başlar.',
    icon: PenTool,
    tier: 'bronze',
    category: 'writer_production',
    conditionDescription: 'Peş peşe 3 gün boyunca her gün en az 300 kelime yazma.',
  },
  steady_pen_7: {
    id: 'steady_pen_7',
    title: 'İstikrarlı Kalem (7 Gün)',
    description: 'Sarsılmaz bir yazma ritmi tutturdun.',
    icon: PenTool,
    tier: 'silver',
    category: 'writer_production',
    conditionDescription: 'Peş peşe 7 gün boyunca her gün en az 300 kelime yazma.',
  },
  steady_pen_30: {
    id: 'steady_pen_30',
    title: 'İstikrarlı Kalem (30 Gün)',
    description: 'Sen gerçek bir yazarsın.',
    icon: PenTool,
    tier: 'gold',
    category: 'writer_production',
    conditionDescription: 'Peş peşe 30 gün boyunca her gün en az 300 kelime yazma.',
  },
  magic_touch: {
    id: 'magic_touch',
    title: 'Sihirli Dokunuş',
    description: 'Dış dünyadaki kelimelerini platforma taşıdın.',
    icon: Wand2,
    tier: 'bronze',
    category: 'writer_production',
    conditionDescription: 'Dışarıdan bir Word belgesini veya metni sisteme aktarma.',
  },

  // --- 2. Yayınlama ve Kilometre Taşları (Yazarlar İçin) ---
  stage_dust: {
    id: 'stage_dust',
    title: 'Sahne Tozu',
    description: 'İlk eserini okurlarla buluşturdun.',
    icon: Theater,
    tier: 'special',
    category: 'writer_publishing',
    conditionDescription: 'Platformda ilk bölümü herkese açık olarak yayınlama.',
  },
  serial_producer_10: {
    id: 'serial_producer_10',
    title: 'Seri Üretici (10)',
    description: 'Hikayen şekillenmeye başladı.',
    icon: Layers,
    tier: 'bronze',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayede 10. bölüme ulaşma.',
  },
  serial_producer_20: {
    id: 'serial_producer_20',
    title: 'Seri Üretici (20)',
    description: 'İstikrarlı bir şekilde ilerliyorsun.',
    icon: Layers,
    tier: 'bronze',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayede 20. bölüme ulaşma.',
  },
  serial_producer_30: {
    id: 'serial_producer_30',
    title: 'Seri Üretici (30)',
    description: 'Kurgun derinleşiyor.',
    icon: Layers,
    tier: 'silver',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayede 30. bölüme ulaşma.',
  },
  serial_producer_40: {
    id: 'serial_producer_40',
    title: 'Seri Üretici (40)',
    description: 'Kusursuz bir ritim.',
    icon: Layers,
    tier: 'silver',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayede 40. bölüme ulaşma.',
  },
  serial_producer_50: {
    id: 'serial_producer_50',
    title: 'Seri Üretici (50)',
    description: 'Devasa bir destan yazıyorsun.',
    icon: Layers,
    tier: 'gold',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayede 50. bölüme ulaşma.',
  },
  finalist: {
    id: 'finalist',
    title: 'Finalist',
    description: 'Her güzel şeyin bir sonu vardır. İlk serini bitirdin.',
    icon: CheckCircle2,
    tier: 'gold',
    category: 'writer_publishing',
    conditionDescription: 'Platformda ilk kez bir hikayenin durumunu "Tamamlandı" olarak işaretleme.',
  },
  first_crowd_100: {
    id: 'first_crowd_100',
    title: 'İlk Kalabalık (100)',
    description: 'Eserin 100 farklı okura ulaştı.',
    icon: Users,
    tier: 'bronze',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayenin 100 tekil okumaya ulaşması.',
  },
  first_crowd_1000: {
    id: 'first_crowd_1000',
    title: 'İlk Kalabalık (1000)',
    description: 'Eserin dev bir kitleye ulaştı.',
    icon: Users,
    tier: 'gold',
    category: 'writer_publishing',
    conditionDescription: 'Bir hikayenin 1.000 tekil okumaya ulaşması.',
  },
  controversial: {
    id: 'controversial',
    title: 'Tartışma Yaratan',
    description: 'Yazdıkların insanları konuşturuyor.',
    icon: MessageSquare,
    tier: 'silver',
    category: 'writer_publishing',
    conditionDescription: 'Yayınlanan tek bir bölümün 20\'den fazla yorum alması.',
  },
  silver_tongue: {
    id: 'silver_tongue',
    title: 'Söz Gümüşse',
    description: 'Okurlarınla arandaki bağ çok güçlü.',
    icon: CornerDownRight,
    tier: 'silver',
    category: 'writer_publishing',
    conditionDescription: 'Okuyucularından gelen yorumlara 50 kez yanıt verme.',
  },

  // --- 3. Tüketim ve Keşif (Okurlar İçin) ---
  first_page: {
    id: 'first_page',
    title: 'İlk Sayfa',
    description: 'Readixon dünyasına ilk adım.',
    icon: BookOpen,
    tier: 'special',
    category: 'reader_consumption',
    conditionDescription: 'Bir hikayenin ilk bölümünü sonuna kadar okuma.',
  },
  bookworm_1: {
    id: 'bookworm_1',
    title: 'Kitap Kurdu (Seviye 1)',
    description: 'Sayfalar arasında kaybolmaya başladın.',
    icon: BookOpen,
    tier: 'bronze',
    category: 'reader_consumption',
    conditionDescription: 'Toplamda 10 farklı bölüm okuma.',
  },
  bookworm_2: {
    id: 'bookworm_2',
    title: 'Kitap Kurdu (Seviye 2)',
    description: 'Okumak senin için bir yaşam tarzı.',
    icon: BookOpen,
    tier: 'silver',
    category: 'reader_consumption',
    conditionDescription: 'Toplamda 50 farklı bölüm okuma.',
  },
  bookworm_3: {
    id: 'bookworm_3',
    title: 'Kitap Kurdu (Seviye 3)',
    description: 'Platformun en saygın okurlarından biri oldun.',
    icon: BookOpen,
    tier: 'gold',
    category: 'reader_consumption',
    conditionDescription: 'Toplamda 100 farklı bölüm okuma.',
  },
  binge_reader: {
    id: 'binge_reader',
    title: 'Maratoncu',
    description: 'Sürükleyici kurgudan kopamıyorsun.',
    icon: Star,
    tier: 'silver',
    category: 'reader_consumption',
    conditionDescription: 'Aynı hikayenin peş peşe en az 5 bölümünü tek oturuşta okuma.',
  },
  librarian: {
    id: 'librarian',
    title: 'Kütüphaneci',
    description: 'Kişisel kütüphanen giderek büyüyor.',
    icon: Library,
    tier: 'bronze',
    category: 'reader_consumption',
    conditionDescription: 'Okuma listesine veya kütüphanesine 10 farklı hikaye ekleme.',
  },
  night_watch: {
    id: 'night_watch',
    title: 'Gece Nöbeti',
    description: 'Gerçek okurlar geceleri yaşar.',
    icon: Clock,
    tier: 'silver',
    category: 'reader_consumption',
    conditionDescription: 'Gece 00:00 ile 04:00 saatleri arasında en az 3 bölüm okuma.',
  },

  // --- 4. Etkileşim ve Sadakat (Okurlar İçin) ---
  first_voice: {
    id: 'first_voice',
    title: 'İlk Ses',
    description: 'Bölümü ilk sen okudun ve ilk sen yorumladın.',
    icon: MessageCircle,
    tier: 'special',
    category: 'reader_interaction',
    conditionDescription: 'Yeni yayınlanan bir bölüme ilk yorumu atan kişi olma.',
  },
  critic: {
    id: 'critic',
    title: 'Eleştirmen',
    description: 'Yazarlara değer katan düşüncelerin var.',
    icon: MessageSquare,
    tier: 'silver',
    category: 'reader_interaction',
    conditionDescription: 'Farklı hikayelere toplamda 50 yapıcı yorum bırakma.',
  },
  generous_reader: {
    id: 'generous_reader',
    title: 'Cömert Okur',
    description: 'Emeğe saygın sonsuz, desteklerini esirgemiyorsun.',
    icon: Heart,
    tier: 'gold',
    category: 'reader_interaction',
    conditionDescription: 'Okuduğu bölümlere toplamda 100 kez beğeni/oy verme.',
  },
  authors_favorite: {
    id: 'authors_favorite',
    title: 'Yazarın Gözdesi',
    description: 'Yazar senin yorumunu özel buldu.',
    icon: UserPlus,
    tier: 'diamond',
    category: 'reader_interaction',
    conditionDescription: 'Yaptığı bir yorumun bölümün yazarı tarafından beğenilmesi veya yanıtlanması.',
  },
  addicted: {
    id: 'addicted',
    title: 'Müptela',
    description: 'Readixon artık günlük rutinin.',
    icon: Calendar,
    tier: 'silver',
    category: 'reader_interaction',
    conditionDescription: 'Peş peşe 7 gün boyunca her gün en az 1 bölüm okuma.',
  },
  readixon_veteran: {
    id: 'readixon_veteran',
    title: 'Readixon Gediklisi',
    description: 'Platformun demirbaşı oldun.',
    icon: Award,
    tier: 'gold',
    category: 'reader_interaction',
    conditionDescription: '30 günlük kesintisiz okuma serisine ulaşma.',
  },
};
