export const POPULAR_TAGS = [
  { id: 'sci-fi', label: 'Bilim Kurgu' },
  { id: 'fantasy', label: 'Fantastik' },
  { id: 'romance', label: 'Romantik' },
  { id: 'thriller', label: 'Gerilim' },
  { id: 'mystery', label: 'Gizem' },
  { id: 'young-adult', label: 'Genç Kurgu' },
  { id: 'horror', label: 'Korku' },
  { id: 'adventure', label: 'Macera' },
  { id: 'historical', label: 'Tarihi Kurgu' },
  { id: 'literary-fiction', label: 'Edebi Kurgu' },
  { id: 'action', label: 'Aksiyon' },
  { id: 'crime', label: 'Polisiye' },
  { id: 'drama', label: 'Dram' },
  { id: 'comedy', label: 'Komedi' },
  { id: 'dystopian', label: 'Distopya' },
  { id: 'paranormal', label: 'Paranormal' },
  { id: 'vampire', label: 'Vampir / Kurtadam' },
  { id: 'psychological', label: 'Psikolojik Kurgu' },
  { id: 'poetry', label: 'Şiir' },
  { id: 'short-story', label: 'Kısa Hikaye' },
  { id: 'adult', label: 'Yetişkin (+18)' },
];
