export const POPULAR_TAGS = [
  { id: 'webtoon', label: 'Webtoon' },
  { id: 'fantasy', label: 'Fantastik' },
  { id: 'sci-fi', label: 'Bilim Kurgu' },
  { id: 'action', label: 'Aksiyon' },
  { id: 'romance', label: 'Romantik' },
  { id: 'isekai', label: 'İsekai / Reenkarnasyon' },
  { id: 'system', label: 'Sistem / Seviye Atlama' },
  { id: 'martial-arts', label: 'Dövüş Sanatları' },
  { id: 'thriller', label: 'Gerilim' },
  { id: 'mystery', label: 'Gizem' },
  { id: 'adventure', label: 'Macera' },
  { id: 'supernatural', label: 'Doğaüstü' },
  { id: 'dark-fantasy', label: 'Karanlık Fantazi' },
  { id: 'horror', label: 'Korku' },
  { id: 'dystopian', label: 'Distopya' },
  { id: 'cyberpunk', label: 'Siberpunk' },
  { id: 'post-apocalyptic', label: 'Kıyamet Sonrası' },
  { id: 'mythology', label: 'Mitoloji' },
  { id: 'crime', label: 'Polisiye' },
  { id: 'drama', label: 'Dram' },
  { id: 'comedy', label: 'Komedi' },
  { id: 'young-adult', label: 'Genç Kurgu' },
  { id: 'school', label: 'Okul / Gençlik' },
  { id: 'slice-of-life', label: 'Günlük Yaşam' },
  { id: 'psychological', label: 'Psikolojik Kurgu' },
  { id: 'historical', label: 'Tarihi Kurgu' },
  { id: 'literary-fiction', label: 'Edebi Kurgu' },
  { id: 'fanfiction', label: 'Hayran Kurgu' },
  { id: 'paranormal', label: 'Paranormal' },
  { id: 'vampire', label: 'Vampir / Kurtadam' },
  { id: 'short-story', label: 'Kısa Hikaye' },
  { id: 'poetry', label: 'Şiir' },
  { id: 'adult', label: 'Yetişkin (+18)' },
];

